### ISSUE TITLE
Not work with Carthage

### ISSUE THREAD

**Issue by Hokila** [optimizely/objective-c-sdk#119]
install and launch immediately
it's work when use other framework

`
dyld: Library not loaded: @rpath/FMDB.framework/FMDB
  Referenced from: /private/var/containers/Bundle/Application/3B1F6C3D-6C21-4702-BBE6-6ACDB9E6B01B/testCatheage.app/Frameworks/OptimizelySDKCore.framework/OptimizelySDKCore
  Reason: image not found
`

I create a sample app at https://github.com/Hokila/testCatheage
could you tell me what's wrong?

**Comment by alda-optimizely** [comment]
You'll need to link the FMDB framework as well. Please refer to the new README on instructions for getting Carthage set up:

https://github.com/optimizely/objective-c-sdk/blob/devel/README.md

This new README notes will be merged into master on our next release.

**Comment by Hokila** [comment]
It's work.thanks
