### ISSUE TITLE
event tags

### ISSUE THREAD

**Issue by radelcom** [optimizely/objective-c-sdk#128]
Im trying to use the event tagging API from this [doc](https://developers.optimizely.com/x/solutions/sdks/reference/?language=objectivec#event-tags). However, the code doesnt look like available in the latest iOS SDK v1.0.1?

NSDictionary *attributes = @{@"device" : @"iPhone", @"ad_source" : @"my_campaign"};

NSDictionary *eventTags = @{
  @"purchasePrice" : @64.32,
  @"category" : @"shoes",
  @"revenue": @6432  // reserved "revenue" tag
};

[optimizely track:@"my_conversion"
           userId:@"user123"
       attributes:attributes
       eventTags:eventTags];

**Comment by alda-optimizely** [comment]
this feature is in 1.1.0
