### ISSUE TITLE
Carthage installation failing on dependancy JSONModel

### ISSUE THREAD

**Issue by AJ9UNiDAYS** [optimizely/objective-c-sdk#137]
Hello, 

When adding the following to my cartfile JSONModel fails to build:

github "optimizely/objective-c-sdk"
github "jsonmodel/jsonmodel"
github "ccgus/fmdb"

Error produced via carthage:

```
*** Building scheme "JSONModel" in JSONModel.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /path_to_project/Carthage/Checkouts/jsonmodel/JSONModel.xcodeproj -scheme JSONModel -configuration Release -derivedDataPath /Users/work/Library/Caches/org.carthage.CarthageKit/DerivedData/jsonmodel/1.7.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

I realise this isn't Optimizely failing but does stop me using your SDK.

**Comment by AJ9UNiDAYS** [comment]
This issue is resolved on the latest commit of the master branch for JSONModel.

This cartfile builds and runs as expected:

```
github "optimizely/objective-c-sdk" "iOS-1.1.0"
github "jsonmodel/jsonmodel" "1e80ecaec8314c7d367676ed0e8545c10c563612"
github "ccgus/fmdb" "2.6.2"

```

**Comment by alda-optimizely** [comment]
Awesome. Thanks for checking this @AJ9UNiDAYS. I will close this out for now. We are waiting for jsonmodel to do a new release before removing this workaround.
