### ISSUE TITLE
OptimizelySDKShared.podspec add framework

### ISSUE THREAD

**Issue by Samback** [optimizely/objective-c-sdk#188]
Please add at podspec file 
`libsqlite3.tbd` framework. Now it shows 58 errors for me till I add it manually.

**Comment by plu** [comment]
+1

**Comment by ignazioc** [comment]
+1

**Comment by kellyroach-optimizely** [comment]
Issue #188 should be resolved on master branch which includes P.R. #196 .
https://github.com/optimizely/objective-c-sdk/pull/196
https://github.com/optimizely/objective-c-sdk/commit/431aef46fa89c049db5561a4c9f6d51856765c83
Expect to see this fix in the next release from master branch.
