### ISSUE TITLE
OPTLYDatafileManagerDefault has super-weird init method

### ISSUE THREAD

**Issue by roddi** [optimizely/objective-c-sdk#262]
```
+ (nullable instancetype)init:(nonnull OPTLYDatafileManagerBuilderBlock)builderBlock {
    return [[self alloc] initWithBuilder:[OPTLYDatafileManagerBuilder builderWithBlock:builderBlock]];
}
```
This stopped being usable with Swift 4.2

Please stick to generally accepted programming patterns and do not invent weird stuff. Calling a **static** method `init:` and giving it a parameter is asking for trouble…

**Comment by roddi** [comment]
same for `OPTLYManager`

**Comment by kellyroach-optimizely** [comment]
Thanks for the feedback and we're very open to considering suggestions for improvement.
What method signatures would you like these API's to have to address this concern?

**Comment by PetrPrazak** [comment]
Just please make the `initWithBuilder` public, that'll do.

**Comment by jamesruston** [comment]
Any idea when this will be fixed?

**Comment by kellyroach-optimizely** [comment]
This issue is now being tracked internally by JIRA ticket OASIS-3149 .

**Comment by jamesruston** [comment]
As a temporary workaround the method can still be called if you wrap it in backticks.
```swift
OPTLYDatafileManagerDefault.`init` { builder in
    // Do stuff
}
```

**Comment by thomaszurkan-optimizely** [comment]
@roddi we are closing this with the release of 2.1.  We have deprecated the static init method.  We will remove it in subsequent releases.  Thank you so much for pointing this out!
