### ISSUE TITLE
Synchronous Save Event to Database Causes Poor Performance

### ISSUE THREAD

**Issue by jerelevine** [optimizely/objective-c-sdk#276]
https://github.com/optimizely/objective-c-sdk/blob/6c32ba376f7225a311f36bb73233b434de79a12a/OptimizelySDKShared/OptimizelySDKShared/OPTLYEventDataStore.m#L60-L65

Synchronously saving events is causing poor performance when requesting events quickly. It has caused me to instead cache the data after it has been fetched once. It seems odd that this isn't an asynchronous save to the database considering the response is only logged and not needed at the time of processing.

**Comment by mikeproeng37** [comment]
Thanks for raising this. We'll look into it and get back to you.

**Comment by thomaszurkan-optimizely** [comment]
This is fixed in the 3.0 sdk release.
