### ISSUE TITLE
Bitcode error on Xcode10 

### ISSUE THREAD

**Issue by Winnie90** [optimizely/objective-c-sdk#278]
When building our project for our enterprise we come across this issue with bitcode:
Bundle only contains bitcode-marker 

We are manually installing the framework to improve build times. We have the suggested run script in our build phase and this was fine with Xcode 9.4.. The only difference is the new build system in Xcode 10.

```+ xcodebuild -exportArchive -archivePath ./archive.xcarchive -exportPath ./products -exportOptionsPlist './Build Scripts/ExportOptions-Enterprise.plist'
2018-06-27 12:22:43.217 xcodebuild[34625:6042695] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jd/5thvvccs3l10mnxr5sr4bxfr0000gn/T/BBCiPlayer-Enterprise_2018-06-27_12-22-43.205.xcdistributionlogs'.
error: exportArchive: Failed to verify bitcode in OptimizelySDKiOS.framework/OptimizelySDKiOS:
error: Bundle only contains bitcode-marker /var/folders/jd/5thvvccs3l10mnxr5sr4bxfr0000gn/T/XcodeDistPipeline.VTn/Root/Payload/BBCiPlayer-Enterprise.app/Frameworks/OptimizelySDKiOS.framework/OptimizelySDKiOS (armv7)

Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in OptimizelySDKiOS.framework/OptimizelySDKiOS:
error: Bundle only contains bitcode-marker /var/folders/jd/5thvvccs3l10mnxr5sr4bxfr0000gn/T/XcodeDistPipeline.VTn/Root/Payload/BBCiPlayer-Enterprise.app/Frameworks/OptimizelySDKiOS.framework/OptimizelySDKiOS (armv7)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in OptimizelySDKiOS.framework/OptimizelySDKiOS:
error: Bundle only contains bitcode-marker /var/folders/jd/5thvvccs3l10mnxr5sr4bxfr0000gn/T/XcodeDistPipeline.VTn/Root/Payload/BBCiPlayer-Enterprise.app/Frameworks/OptimizelySDKiOS.framework/OptimizelySDKiOS (armv7)

}

** EXPORT FAILED **

**Comment by thomaszurkan-optimizely** [comment]
@Winnie90 we believe this is fixed with the release of 2.1.2. Please let us know if you are still having problems.

**Comment by AM-lu** [comment]
@thomaszurkan-optimizely 
hi 
could you please tell me how you fix this error?
same error happened in my project.

**Comment by gurjnderSingh** [comment]
During making of build **uncheck** the **Rebuild from Bitcode**. option and add the following script under Build phases.

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done

![screen shot 2018-10-11 at 10 58 22 am](https://user-images.githubusercontent.com/12212137/46784963-d258a200-cd4d-11e8-8860-c5dd383ba327.png)

**Comment by thomaszurkan-optimizely** [comment]
@AM-lu  

What version of the sdk?
What version of xcode?
How are you installing sdk (carthage/cocoapods)?
How are you building the sdk?
Assume this is for release?

Thanks!

**Comment by AM-lu** [comment]
hi
@thomaszurkan-optimizely 

First of all, I must say I am not a user of optimizely.

In my Project, we use another different SDK,
All is work well until Xcode9, but when I update to Xcode10, try to archive my app, the similar error was happen.

error: Bundle only contains bitcode-marker

**Comment by teffi** [comment]
@AM-lu  where you able to solve this? I'm encountering the same issue.

**Comment by thomaszurkan-optimizely** [comment]
I'm going to go ahead and close this since we are not having problems with the latest version of xcode 10 and we have made a fix. Please feel free to reopen if you feel this was an error.
