### ISSUE TITLE
Optimizely not building on Xcode 10 beta 5 / 6

### ISSUE THREAD

**Issue by Nonnus** [optimizely/objective-c-sdk#297]
As we want to start preparing for next month iOS 12 release,
we noticed that latest release of Optimizely is not building on latest Xcode beta,
any plans to support it?

**Comment by thomaszurkan-optimizely** [comment]
https://github.com/optimizely/objective-c-sdk/pull/300

**Comment by Nonnus** [comment]
@thomaszurkan-optimizely fyi, i pulled that specific branch (commit c00bc97ebeba68c5eedbe91b42d5dac98c2e7c4c) using carthage and tried to build it using the latest beta 6, however i still got compile errors and was not able to build the sdk

here it the xcodebuild log:
[carthage-xcodebuild.yHduRl.log](https://github.com/optimizely/objective-c-sdk/files/2285979/carthage-xcodebuild.yHduRl.log)

**Comment by jeremycbutler** [comment]
@thomaszurkan-optimizely I am receiving the same errors as @Nonnus on this branch when using Carthage. I was able to temporarily fix this by switching the Build System to Legacy (Xcode->File->Workspace Settings->Build System->Legacy Build System).

**Comment by thomaszurkan-optimizely** [comment]
@Nonnus @jeremycbutler Did you guys try removing derived data, clearing cache and recompiling?  We are trying to get out a patch for xcode 10.  Thanks!

**Comment by ecompton3** [comment]
@thomaszurkan-optimizely is there any update on this? Oddly enough I'm able to build on Xcode 10 but it fails to compile when I try to build for testing. I've cleaned and deleted derived data. Verified that the build only fails when adding the Pod to my existing application

**Comment by jeremycbutler** [comment]
@thomaszurkan-optimizely Yes, I made sure to remove derived data, clear the cache and recompile. It looks like you guys have a fix coming through in the PR's if I read it right...I'll be looking out for it!

**Comment by thomaszurkan-optimizely** [comment]
@jeremycbutler @ecompton3 This should be cleared up in release 2.1.2.  Can you give it a try?  I will wait to close this.

**Comment by thomaszurkan-optimizely** [comment]
Closing since this issue was addressed with 2.1.2 release

**Comment by jeremycbutler** [comment]
@thomaszurkan-optimizely Sorry, just now seeing this somehow. Tried it with 2.1.2 and all is good! Thank you!
