### ISSUE TITLE
Feature tests always send experiment impression

### ISSUE THREAD

**Issue by chillpop** [optimizely/objective-c-sdk#328]
With A/B tests, you have the option of activating the experiment to send an impression, or getting an existing variation without sending an impression.

Feature-based experiments can only easily be accessed using `isFeatureEnabled` which will always send an impression for the experiment.

It would be helpful to be able to get the existing variation for feature-based experiments without sending an impression.  Especially since billing may be tied to impressions.

**Comment by jaeopt** [comment]
We introduced a new api set for decision to swift-sdk, which includes many new features including this option. 
The new decide api has been implemented in swift-sdk only (not in objective-c-sdk).
