### ISSUE TITLE
Crash  in OPTLYFMDBDatabase.m line 1123

### ISSUE THREAD

**Issue by mackoj** [optimizely/objective-c-sdk#360]
I have this crash in my app can you help me please ?

Crashed: optlyfmdb.<OPTLYFMDBDatabaseQueue: 0x28274e220>

http://crashes.to/s/9752b87a219

**Comment by thomaszurkan-optimizely** [comment]
@mackoj I see that you have another thread doing a open db on sqlite.  Do you know whether you are compiled for thead safe sqlite? SQLITE_THREADSAFE=1
https://www.sqlite.org/threadsafe.html.  I would bet that is the issue.

**Comment by mackoj** [comment]
I will try thanks 🙏

**Comment by thomaszurkan-optimizely** [comment]
@mackoj how's it going?  Can we close these?

**Comment by mackoj** [comment]
I have made the modifications but the code is not in production yet.

**Comment by thomaszurkan-optimizely** [comment]
I'm going to go ahead and close this.  Please feel free to reopen if you are still having problems.  Thanks!

**Comment by mackoj** [comment]
It's fix thanks.
Please consider adding somewhere in the documentation or/and in the podspec  `SQLITE_THREADSAFE=1` in order to fix this issue for every one.

Thanks @thomaszurkan-optimizely
