### ISSUE TITLE
Crash in OPTLYFMDBDatabase.m line 209

### ISSUE THREAD

**Issue by mackoj** [optimizely/objective-c-sdk#361]
I have this crash in my app can you help me please ?

Crashed: NSOperationQueue 0x280a04260 (QOS: UNSPECIFIED)

http://crashes.to/s/fcf7f0c2771

**Comment by thomaszurkan-optimizely** [comment]
I'm going to go ahead and close this. Please feel free to reopen if you are still having problems.  Thanks!

**Comment by mackoj** [comment]
It's fix thanks.
Please consider adding somewhere in the documentation or/and in the podspec  `SQLITE_THREADSAFE=1` in order to fix this issue for every one.

Thanks @thomaszurkan-optimizely

**Comment by thomaszurkan-optimizely** [comment]
@mackoj great suggestion!  Will do.
