### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by bdrelling** [optimizely/objective-c-sdk#437]
Will there be any support for Swift Package Manager?

**Comment by jaeopt** [comment]
We currently have no plan to add SPM support to Objective-c SDK. Instead, you can use our new Swift SDK (https://github.com/optimizely/swift-sdk), which supports SPM.

**Comment by bdrelling** [comment]
@jaeopt Thanks, and understood. We didn't even know that library existed. Does it have 1:1 feature parity?

**Comment by bdrelling** [comment]
Nevermind. I can see the answer in the Release:

>This modernized version of the SDK is meant to replace the Objective-C SDK.

Thank you. Closing issue.
