### ISSUE TITLE
Certificate pinning is half implemented and cause us issue when archiving

### ISSUE THREAD

**Issue by mackoj** [optimizely/objective-c-sdk#438]
We think that this #427 has caused us the issue, each time we try to compile the project for archiving.

:x:  error: /Users/vagrant/git/PagesJaunes/Pods/OptimizelySDKCore/OptimizelySDKCore/Resources/logxDump.cer: No such file or directory (in target 'OptimizelySDKCore-OptimizelySDKCoreiOS' from project 'Pods')

Can we remove the CER that don't seem to be used anywhere without problem ?

You seems to have a fix https://github.com/optimizely/objective-c-sdk/pull/433 but don't seem really eager to merge it. We have this issue for month now why don't you fix it ?

**Comment by jaeopt** [comment]
@mackoj The bundled certs are designed not to affect users who do not need SSL pinning. We confirmed that pod downloads the certs and archives app ok. Can you try again after cleaning up old Pods? If you still have the issue after cleaning up, please share more info (pod and xcode versions). Thanks!

**Comment by jaeopt** [comment]
Regarding #433 , we decided to put SSL pinning support on hold for now and closed the PR.

**Comment by mackoj** [comment]
Please consider removing them if they are not needed.

Cocoapods 1.8.3
Xcode 11.2
macOS Mojave 10.14.6
OptimizelySDKCore 3.1.2
OptimizelySDKDatafileManager 3.1.2
OptimizelySDKEventDispatcher 3.1.2
OptimizelySDKShared 3.1.2
OptimizelySDKUserProfileService 3.1.2
OptimizelySDKiOS 3.1.2

```
CpResource /Users/vagrant/git/PagesJaunes/Pods/OptimizelySDKCore/OptimizelySDKCore/Resources/logxDump.cer /Users/vagrant/Library/Developer/Xcode/DerivedData/PagesJaunes-crszfxggdvvqaiajzoejfzhrpzfz/Build/Intermediates.noindex/ArchiveIntermediates/PagesJaunes/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OptimizelySDKCoreiOS.bundle/logxDump.cer (in target 'OptimizelySDKCore-OptimizelySDKCoreiOS' from project 'Pods')
    cd /Users/vagrant/git/PagesJaunes/Pods
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/vagrant/git/PagesJaunes/Pods/OptimizelySDKCore/OptimizelySDKCore/Resources/logxDump.cer /Users/vagrant/Library/Developer/Xcode/DerivedData/PagesJaunes-crszfxggdvvqaiajzoejfzhrpzfz/Build/Intermediates.noindex/ArchiveIntermediates/PagesJaunes/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OptimizelySDKCoreiOS.bundle
error: /Users/vagrant/git/PagesJaunes/Pods/OptimizelySDKCore/OptimizelySDKCore/Resources/logxDump.cer: No such file or directory (in target 'OptimizelySDKCore-OptimizelySDKCoreiOS' from project 'Pods')
** ARCHIVE FAILED **
The following build commands failed:
	CpResource /Users/vagrant/git/PagesJaunes/Pods/OptimizelySDKCore/OptimizelySDKCore/Resources/logxDump.cer /Users/vagrant/Library/Developer/Xcode/DerivedData/PagesJaunes-crszfxggdvvqaiajzoejfzhrpzfz/Build/Intermediates.noindex/ArchiveIntermediates/PagesJaunes/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OptimizelySDKCoreiOS.bundle/logxDump.cer
(1 failure)
Archive failed, error: exit status 65
```

In order to make our build work we have to remove them from the Pods.xcodeproj > OptimizelySDKCore-OptimizelySDKCoreiOS > build phases.

<img width="640" alt="Capture d’écran 2019-10-22 à 22 20 41" src="https://user-images.githubusercontent.com/661647/67329384-0ea30e80-f51b-11e9-92f3-538516ac000d.png">

**Comment by mackoj** [comment]
This occur only when archiving

**Comment by jaeopt** [comment]
@mackoj Thanks for the info. Since it fails only when archiving (certs copied ok for debug build), I guess it's not a pod download issue. We'll look into it more and get you updated.
Unfortunately, we cannot remove certs for now, but will consider it.
