### ISSUE TITLE
Install docs appear to 404

### ISSUE THREAD

**Issue by djds23** [optimizely/objective-c-sdk#447]
This URL: https://docs.developers.optimizely.com/full-stack/docs/install-the-ios-and-tvos-sdks

Returns this webpage: 
![Screen Shot 2020-08-05 at 4 43 47 PM](https://user-images.githubusercontent.com/5833968/89462236-1abf2c00-d73b-11ea-8ccf-a6c81877d7f0.png)

The URL linked above is currently in the README for this library.

**Comment by jaeopt** [comment]
@djds23 Thanks for letting us know. It'll be fixed.
