### ISSUE TITLE
Compilation is broken on Xcode 12

### ISSUE THREAD

**Issue by danielgalasko** [optimizely/objective-c-sdk#448]
When building with Xcode 12 with parallel build optimisations, Optimizely does not build. I am highlighting an example below

<img width="770" alt="93474411-9940e900-f8f7-11ea-8c50-06fa43becc3d" src="https://user-images.githubusercontent.com/4479146/93483257-eecdc380-f900-11ea-9b2a-fa1778fdd6ad.png">

To reproduce simply pod install Optimizely to any project (Xcode 12) with parallelisation on and attempt to build.

It fails because the spec definitions for most of the frameworks are missing the proper dependencies. See the user profile service for example: https://github.com/optimizely/objective-c-sdk/blob/master/OptimizelySDKUserProfileService.podspec#L19

Notice how it does not include Core but it definitely relies on Core. This can be fixed by adding the relevant dependencies. In our project we manually linked all Optimizely frameworks against their missing counterparts as you can see below where the new framework has a higher prominence and alpha than the ones automatically linked by pods.

<img width="283" alt="Screenshot 2020-09-17 at 16 03 35" src="https://user-images.githubusercontent.com/4479146/93483487-22a8e900-f901-11ea-81e8-764e155a0a6c.png">

**Comment by jaeopt** [comment]
@danielgalasko Thanks for reporting. We're looking into it and get you updated.

**Comment by danielgalasko** [comment]
Awesome @jaeopt much appreciated 😄

**Comment by mattiacantalu** [comment]
Any news @jaeopt ? We're stuck in the same situation :(

**Comment by mattiacantalu** [comment]
3.1.4 is out, but it has same issues for me. 

Workaround: use _Legacy Build System_. it works for me.

**Comment by jaeopt** [comment]
@danielgalasko Can you try with the legacy build system that @mattiacantalu suggested?

**Comment by jaeopt** [comment]
@danielgalasko @mattiacantalu We just released a patch (3.1.5) with a fix for this Xcode-12 build issue. Please give it a try and let us know if it works for you. Tx!

**Comment by mattiacantalu** [comment]
Thank you @jaeopt ! Anyway we just moved to the swift version of the sdk 😜

**Comment by jaeopt** [comment]
Great to hear that! It's a smart move.

**Comment by danielgalasko** [comment]
Thanks folks 🙏 

Since this was a critical blocker for us we moved to the Swift SDK, we also linked it all manually just so we could submit.

Thank you ❤️
