### ISSUE TITLE
Still having build errors on 3.1.4 on XCode 12

### ISSUE THREAD

**Issue by AshleyDeng** [optimizely/objective-c-sdk#455]
Hi, thanks for getting 3.1.4 up to address the build errors on XCode 12.

Comparing the 3.1.3 (https://github.com/optimizely/objective-c-sdk/issues/448), the number of build errors goes down but there are some errors still remaining. 

![Screen Shot 2020-09-24 at 3 57 22 PM](https://user-images.githubusercontent.com/3332584/94209099-b42bd400-fe88-11ea-89ca-ec3d417ef053.png)

Thanks again for the hard work!

**Comment by mattiacantalu** [comment]
Workaround: use _Legacy Build System_. it works for me.

**Comment by jaeopt** [comment]
Great! We'll continue investigation for better solutions.

**Comment by Danny-Driscoll** [comment]
@AshleyDeng @mattiacantalu With 3.1.4 we were addressing a separate bucketing behavior issue in the obj-c SDK, we are still looking into whether a fix for these XCode parallel code build issues will be feasible for the Objective-C SDK. 

Our recommendation in general is to move to our [Swift SDK](https://github.com/optimizely/swift-sdk) at your next upgrade opportunity, which will be our primary SDK for new iOS feature development moving forward. https://docs.developers.optimizely.com/full-stack/docs/migrate-to-swift-sdk

For the time being as @mattiacantalu cited the Legacy Build System should another workaround option until a migration is possible

**Comment by AshleyDeng** [comment]
@Danny-Driscoll Thanks for the response. And @mattiacantalu Thanks for the workaround!

We've investigated the proposed options but we think we will wait for the real fix. Reasons are:
1. We cannot use the `Legacy Build System` due to some business reasons.
2. We cannot migrate to your Swift SDK just yet as there are lots of regression testings needed for the migration, which we are not comfortable in doing so yet.

**Comment by jaeopt** [comment]
@AshleyDeng We just released a patch (3.1.5) with a fix for this Xcode-12 build issue. Please give it a try and let us know if it works for you. Tx!
